# Generated by Django 5.0.7 on 2024-07-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=15)),
            ],
        ),
    ]
